version: '2'
services:
  app:
    image: 'votacao-api:latest'
    ports:
      - 8080:8080
    build:
      context: .
    container_name: votacao-api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
